version: 2

run:
  timeout: 3m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - varnamelen
    - cyclop # duplicate of gocyclo
    - bodyclose # Too many false positives
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - wrapcheck
    - noctx
    - lll
    - forbidigo
    - ireturn
    - depguard
    - tagalign
    - mnd
    - exhaustruct
    - perfsprint
    - intrange
    - copyloopvar
    - testifylint

formatters:
  disable:
    - goimports
    - gofumpt

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
